# Generated by Django 3.1.12 on 2026-02-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadtask',
            name='format',
            field=models.CharField(default='mp3', max_length=10),
        ),
        migrations.AddField(
            model_name='downloadtask',
            name='quality',
            field=models.CharField(default='medium', max_length=10),
        ),
    ]
