"""
Django settings for cfe project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import json
import os

# Backend directory (where manage.py resides)
BASE_DIR = Path(__file__).resolve().parent.parent
# Project root directory
PROJECT_ROOT = BASE_DIR.parent
# Frontend directory
FRONTEND_DIR = PROJECT_ROOT / 'frontend'

# Load credentials from file or environment variables (for Docker)
credentialsFile = PROJECT_ROOT.parent.parent / 'credentials/youtubeDownloader.json'
if os.path.exists(credentialsFile):
    credentials = json.load(open(credentialsFile))
    SECRET_KEY = credentials['secretKey']
else:
    # Use environment variable in Docker or generate a default for development
    SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-docker-dev-key-change-in-production')

DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Allow hosts from environment variable or default to localhost
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
SESSION_ENGINE = 'django.contrib.sessions.backends.file'
SESSION_FILE_PATH = BASE_DIR / 'sessions'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'youtube',
    'webpush',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cfe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ FRONTEND_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cfe.wsgi.application'

# Database path - use data directory if running in Docker (check via env var or directory existence)
# For Docker: /app/backend/data/db.sqlite3
# For local dev: /backend/db.sqlite3
if os.environ.get('DOCKER_CONTAINER') or (BASE_DIR / 'data').is_dir():
    DB_DIR = BASE_DIR / 'data'
else:
    DB_DIR = BASE_DIR

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DB_DIR / 'db.sqlite3',
    }
}

WEBPUSH_SETTINGS = {
   "VAPID_PUBLIC_KEY": "BOrK4AGHOT47xPIdwvekq6chhNQyE4NP96_WHX1OHc7JGnr99-KE5t_wWOl_s9Wst_LFEMPSb-X3dGMlkmRaUhk",
   "VAPID_PRIVATE_KEY": "jm0cfkKNQOnDJeiunUzTyhLPTdN4e7v1GFh45vgbT8M",
   "VAPID_ADMIN_EMAIL": "ceenimo9@gmail.com",
}

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


STATICFILES_DIRS = [ FRONTEND_DIR / 'static']
STATIC_URL = 'static/'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'