# Generated by Django 3.1.12 on 2025-05-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadtask',
            name='file_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
