# Generated by Django 3.1.12 on 2025-05-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_downloadtask_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadtask',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
